import type {
  AiProject,
  AlertItem,
  ApprovalItem,
  BudgetLine,
  CashPoint,
  Company,
  DataAsset,
  Deal,
  Fabric,
  MemoItem,
  Member,
  ProductionJob,
  RevenuePoint,
  RndTask,
  ScheduleItem,
  TailorCustomer,
  TailorOrder,
  TaskItem,
  Product,
  Transaction,
  UrgentItem,
} from "./types";

/** 데모 기준일 (서버·클라이언트 렌더 결과를 동일하게 유지하기 위해 고정값 사용) */
export const TODAY = "2026-07-29";
export const TODAY_LABEL = "2026.07.29 (수)";

export const COMPANIES: Record<"tailor" | "corp", Company> = {
  tailor: {
    id: "tailor",
    name: "비앤테일러샵",
    shortName: "비앤테일러샵",
    mark: "B&",
    business: "비스포크 맞춤정장 · 셔츠 제작",
    ceo: "박정열",
    founded: "2016.03",
    employees: 11,
    location: "서울 강남구 청담동",
    tone: "tailor",
  },
  corp: {
    id: "corp",
    name: "AI 소프트웨어 법인",
    shortName: "AI 법인",
    mark: "AI",
    business: "AI 솔루션 개발 · 데이터 분석 · SaaS",
    ceo: "박정열",
    founded: "2023.09",
    employees: 25,
    location: "서울 성동구 성수동",
    tone: "corp",
  },
};

export const COMPANY_LIST: Company[] = [COMPANIES.tailor, COMPANIES.corp];

/* ────────────────────────────────────────────
   요약 지표
   ──────────────────────────────────────────── */

export const SUMMARY = {
  tailor: {
    revenue: 128_450_000,
    revenueDelta: 12.4,
    lastMonthRevenue: 114_280_000,
    todayRevenue: 12_450_000,
    receivable: 38_600_000,
    newConsult: 28,
    inProduction: 61,
    delivery: 18,
    repurchase: 37,
    orderCount: 46,
    fittingCount: 14,
    avgOrderValue: 2_792_000,
    delayRisk: 3,
    fabricAlert: 5,
  },
  corp: {
    revenue: 87_320_000,
    revenueDelta: 8.7,
    lastMonthRevenue: 80_330_000,
    todayRevenue: 3_100_000,
    receivable: 24_000_000,
    projects: 12,
    features: 19,
    rnd: 8,
    headcount: 25,
    devCost: 96_500_000,
    poc: 6,
    paid: 9,
    newContract: 3,
    pipeline: 412_000_000,
    delayIssue: 2,
    rndDueSoon: 2,
    newHire: 1,
  },
  cash: {
    available: 950_000_000,
    tailorAvailable: 412_000_000,
    corpAvailable: 538_000_000,
    plannedSpend: 346_500_000,
    executedRate: 63,
    reserve: 180_000_000,
  },
};

/* ────────────────────────────────────────────
   매출 · 자금 추이
   ──────────────────────────────────────────── */

export const REVENUE_TREND: RevenuePoint[] = [
  { month: "2월", tailor: 92_400_000, corp: 48_600_000 },
  { month: "3월", tailor: 118_700_000, corp: 56_200_000 },
  { month: "4월", tailor: 106_300_000, corp: 63_900_000 },
  { month: "5월", tailor: 111_900_000, corp: 71_400_000 },
  { month: "6월", tailor: 114_280_000, corp: 80_330_000 },
  { month: "7월", tailor: 128_450_000, corp: 87_320_000 },
];

export const REVENUE_TREND_12M: RevenuePoint[] = [
  { month: "8월", tailor: 88_100_000, corp: 21_500_000 },
  { month: "9월", tailor: 95_600_000, corp: 26_800_000 },
  { month: "10월", tailor: 121_300_000, corp: 31_200_000 },
  { month: "11월", tailor: 134_800_000, corp: 34_900_000 },
  { month: "12월", tailor: 142_600_000, corp: 41_300_000 },
  { month: "1월", tailor: 86_900_000, corp: 44_100_000 },
  ...REVENUE_TREND,
];

export const CASH_TREND: CashPoint[] = [
  { month: "2월", tailorIn: 92_400_000, tailorOut: 71_200_000, corpIn: 48_600_000, corpOut: 66_400_000 },
  { month: "3월", tailorIn: 118_700_000, tailorOut: 83_500_000, corpIn: 56_200_000, corpOut: 72_100_000 },
  { month: "4월", tailorIn: 106_300_000, tailorOut: 78_900_000, corpIn: 63_900_000, corpOut: 74_800_000 },
  { month: "5월", tailorIn: 111_900_000, tailorOut: 81_600_000, corpIn: 71_400_000, corpOut: 79_200_000 },
  { month: "6월", tailorIn: 114_280_000, tailorOut: 84_300_000, corpIn: 80_330_000, corpOut: 82_600_000 },
  { month: "7월", tailorIn: 128_450_000, tailorOut: 88_700_000, corpIn: 87_320_000, corpOut: 86_100_000 },
];

/** 비앤테일러샵 매출 구성 */
export const TAILOR_REVENUE_MIX = [
  { name: "비스포크 정장", value: 78_200_000 },
  { name: "셔츠 · 소품", value: 21_400_000 },
  { name: "코트 · 아우터", value: 18_600_000 },
  { name: "수선 · 리폼", value: 6_250_000 },
  { name: "기업 단체복", value: 4_000_000 },
];

/** AI 법인 매출 구성 */
export const CORP_REVENUE_MIX = [
  { name: "SaaS 구독", value: 31_400_000 },
  { name: "SI · 커스터마이징", value: 26_800_000 },
  { name: "PoC 용역", value: 15_120_000 },
  { name: "정부 R&D 과제", value: 10_000_000 },
  { name: "데이터 라이선스", value: 4_000_000 },
];

/* ────────────────────────────────────────────
   비앤테일러샵 : 고객 · 주문 · 원단 · 제작
   ──────────────────────────────────────────── */

export const TAILOR_CUSTOMERS: TailorCustomer[] = [
  {
    id: "C-1042",
    name: "김진우",
    grade: "VIP",
    company: "대현물산 대표",
    phone: "010-2841-77**",
    firstVisit: "2019.04.12",
    lastVisit: "2026.07.18",
    visits: 14,
    totalAmount: 48_600_000,
    preferredFabric: "Ermenegildo Zegna Trofeo 600",
    size: "R 100 / 소매 62 / 총장 74",
    repurchaseScore: 92,
    nextAction: "가을 코트 상담 제안",
  },
  {
    id: "C-0987",
    name: "박지영",
    grade: "VIP",
    company: "세림회계법인 파트너",
    phone: "010-3352-21**",
    firstVisit: "2020.09.03",
    lastVisit: "2026.07.22",
    visits: 11,
    totalAmount: 36_200_000,
    preferredFabric: "Loro Piana Super 130's",
    size: "R 88 / 소매 58 / 총장 68",
    repurchaseScore: 88,
    nextAction: "여름 재킷 가봉 일정 확정",
  },
  {
    id: "C-1188",
    name: "이도현",
    grade: "우수",
    company: "한성엔지니어링 상무",
    phone: "010-9921-40**",
    firstVisit: "2022.02.18",
    lastVisit: "2026.07.11",
    visits: 7,
    totalAmount: 21_400_000,
    preferredFabric: "Dormeuil Amadeus 365",
    size: "R 96 / 소매 61 / 총장 73",
    repurchaseScore: 76,
    nextAction: "예복 2벌 견적 회신",
  },
  {
    id: "C-1230",
    name: "정민수",
    grade: "우수",
    company: "미래에셋 지점장",
    phone: "010-4410-58**",
    firstVisit: "2021.11.09",
    lastVisit: "2026.06.30",
    visits: 6,
    totalAmount: 18_900_000,
    preferredFabric: "Loro Piana Tasmanian",
    size: "R 102 / 소매 63 / 총장 75",
    repurchaseScore: 71,
    nextAction: "재구매 주기 도래, 연락 필요",
  },
  {
    id: "C-1301",
    name: "최유리",
    grade: "신규",
    company: "브랜드컨설팅 아뜰리에 대표",
    phone: "010-7723-19**",
    firstVisit: "2026.07.08",
    lastVisit: "2026.07.24",
    visits: 2,
    totalAmount: 4_300_000,
    preferredFabric: "Vitale Barberis Canonico Perennial",
    size: "R 86 / 소매 57 / 총장 66",
    repurchaseScore: 58,
    nextAction: "첫 착용 후 피드백 확인",
  },
  {
    id: "C-1044",
    name: "한재석",
    grade: "VIP",
    company: "동인건설 부사장",
    phone: "010-2277-63**",
    firstVisit: "2018.06.21",
    lastVisit: "2026.05.29",
    visits: 16,
    totalAmount: 57_100_000,
    preferredFabric: "Ermenegildo Zegna 15milmil15",
    size: "R 104 / 소매 64 / 총장 76",
    repurchaseScore: 83,
    nextAction: "임원 단체 예복 제안",
  },
  {
    id: "C-1276",
    name: "오세훈",
    grade: "일반",
    company: "프리랜서 변호사",
    phone: "010-8890-32**",
    firstVisit: "2024.08.14",
    lastVisit: "2026.04.17",
    visits: 3,
    totalAmount: 8_700_000,
    preferredFabric: "Dormeuil Tonik 2000",
    size: "R 94 / 소매 60 / 총장 72",
    repurchaseScore: 64,
    nextAction: "시즌 프로모션 안내",
  },
  {
    id: "C-1318",
    name: "윤소라",
    grade: "신규",
    company: "제이드메디컬 이사",
    phone: "010-5512-08**",
    firstVisit: "2026.06.02",
    lastVisit: "2026.07.20",
    visits: 3,
    totalAmount: 6_950_000,
    preferredFabric: "Loro Piana Super 130's",
    size: "R 84 / 소매 56 / 총장 65",
    repurchaseScore: 69,
    nextAction: "셔츠 3매 추가 상담",
  },
];

export const TAILOR_ORDERS: TailorOrder[] = [
  {
    id: "ORD-2607-018",
    customer: "김진우",
    customerId: "C-1042",
    item: "3피스 정장 1벌",
    fabric: "Zegna Trofeo 600 / 네이비",
    stage: "납품",
    status: "정상",
    amount: 4_850_000,
    deposit: 2_400_000,
    orderedAt: "2026.06.14",
    fittingAt: "2026.07.16",
    dueAt: "2026.07.29",
    manager: "이정한 실장",
    note: "라펠 폭 8.5cm, 안감 버건디 지정",
  },
  {
    id: "ORD-2607-021",
    customer: "박지영",
    customerId: "C-0987",
    item: "여성 정장 재킷 · 스커트",
    fabric: "Loro Piana Super 130's / 차콜",
    stage: "가봉",
    status: "정상",
    amount: 3_620_000,
    deposit: 1_800_000,
    orderedAt: "2026.06.22",
    fittingAt: "2026.07.30",
    dueAt: "2026.08.12",
    manager: "이정한 실장",
    note: "어깨 패드 최소화 요청",
  },
  {
    id: "ORD-2607-009",
    customer: "이도현",
    customerId: "C-1188",
    item: "예복 정장 2벌",
    fabric: "Dormeuil Amadeus 365 / 미드나잇",
    stage: "제작",
    status: "지연 위험",
    amount: 7_400_000,
    deposit: 3_700_000,
    orderedAt: "2026.06.03",
    fittingAt: "2026.07.09",
    dueAt: "2026.08.05",
    manager: "박선우 팀장",
    note: "원단 추가 입고 대기, 납기 재확인 필요",
  },
  {
    id: "ORD-2607-030",
    customer: "최유리",
    customerId: "C-1301",
    item: "여성 팬츠수트 1벌",
    fabric: "VBC Perennial / 라이트 그레이",
    stage: "원단 선택",
    status: "정상",
    amount: 2_980_000,
    deposit: 1_000_000,
    orderedAt: "2026.07.24",
    fittingAt: null,
    dueAt: "2026.08.28",
    manager: "정하윤 매니저",
    note: "샘플 3종 비교 후 결정 예정",
  },
  {
    id: "ORD-2606-044",
    customer: "한재석",
    customerId: "C-1044",
    item: "캐시미어 코트 1벌",
    fabric: "Zegna 15milmil15 / 카멜",
    stage: "수정",
    status: "정상",
    amount: 5_600_000,
    deposit: 2_800_000,
    orderedAt: "2026.05.29",
    fittingAt: "2026.07.03",
    dueAt: "2026.08.01",
    manager: "박선우 팀장",
    note: "소매 1.5cm 수선 진행 중",
  },
  {
    id: "ORD-2607-033",
    customer: "정민수",
    customerId: "C-1230",
    item: "비즈니스 정장 1벌",
    fabric: "Loro Piana Tasmanian / 네이비 스트라이프",
    stage: "치수 측정",
    status: "정상",
    amount: 3_250_000,
    deposit: 1_600_000,
    orderedAt: "2026.07.26",
    fittingAt: null,
    dueAt: "2026.09.02",
    manager: "정하윤 매니저",
    note: "출장 일정 고려해 가봉 주말 예약",
  },
  {
    id: "ORD-2606-039",
    customer: "오세훈",
    customerId: "C-1276",
    item: "정장 1벌 · 셔츠 2매",
    fabric: "Dormeuil Tonik 2000 / 블랙",
    stage: "제작",
    status: "지연",
    amount: 3_980_000,
    deposit: 1_900_000,
    orderedAt: "2026.05.21",
    fittingAt: "2026.06.28",
    dueAt: "2026.07.25",
    manager: "박선우 팀장",
    note: "봉제 인력 배정 지연, 4일 초과",
  },
  {
    id: "ORD-2607-036",
    customer: "윤소라",
    customerId: "C-1318",
    item: "맞춤 셔츠 3매",
    fabric: "Thomas Mason Journey / 화이트",
    stage: "상담",
    status: "정상",
    amount: 1_050_000,
    deposit: 0,
    orderedAt: "2026.07.27",
    fittingAt: null,
    dueAt: "2026.08.20",
    manager: "정하윤 매니저",
    note: "칼라 형태 2안 제시 예정",
  },
];

export const ORDER_STAGES = [
  "상담",
  "치수 측정",
  "원단 선택",
  "제작",
  "가봉",
  "수정",
  "납품",
] as const;

/** 주문 진행단계별 건수 (이번 달 전체) */
export const ORDER_FUNNEL = [
  { stage: "상담", count: 28, amount: 71_400_000 },
  { stage: "치수 측정", count: 22, amount: 62_800_000 },
  { stage: "원단 선택", count: 19, amount: 55_300_000 },
  { stage: "제작", count: 61, amount: 168_900_000 },
  { stage: "가봉", count: 14, amount: 41_200_000 },
  { stage: "수정", count: 9, amount: 26_100_000 },
  { stage: "납품", count: 18, amount: 52_600_000 },
];

export const FABRICS: Fabric[] = [
  {
    id: "F-101",
    brand: "Ermenegildo Zegna",
    name: "Trofeo 600",
    code: "TRF-600-1247",
    color: "네이비",
    composition: "Wool 100% / 250g",
    stockM: 4.2,
    assignedM: 3.5,
    unitPrice: 210_000,
    status: "재고 부족",
    leadTimeDays: 21,
    updatedAt: "2026.07.28",
    weave: "herringbone",
  },
  {
    id: "F-108",
    brand: "Loro Piana",
    name: "Super 130's",
    code: "LP-130-0884",
    color: "차콜 그레이",
    composition: "Wool 100% / 270g",
    stockM: 5.1,
    assignedM: 4.4,
    unitPrice: 178_000,
    status: "재고 부족",
    leadTimeDays: 18,
    updatedAt: "2026.07.28",
    weave: "twill",
  },
  {
    id: "F-115",
    brand: "Dormeuil",
    name: "Amadeus 365",
    code: "DM-365-2210",
    color: "미드나잇 블루",
    composition: "Wool 100% / 285g",
    stockM: 12.6,
    assignedM: 9.8,
    unitPrice: 156_000,
    status: "발주 권장",
    leadTimeDays: 24,
    updatedAt: "2026.07.27",
    weave: "herringbone",
  },
  {
    id: "F-122",
    brand: "Vitale Barberis Canonico",
    name: "Perennial",
    code: "VBC-PN-0417",
    color: "라이트 그레이",
    composition: "Wool 100% / 240g",
    stockM: 18.4,
    assignedM: 6.2,
    unitPrice: 98_000,
    status: "충분",
    leadTimeDays: 15,
    updatedAt: "2026.07.26",
    weave: "plain",
  },
  {
    id: "F-130",
    brand: "Ermenegildo Zegna",
    name: "15milmil15",
    code: "ZG-15M-3390",
    color: "카멜",
    composition: "Wool 90% Cashmere 10%",
    stockM: 7.8,
    assignedM: 6.0,
    unitPrice: 264_000,
    status: "발주 권장",
    leadTimeDays: 28,
    updatedAt: "2026.07.25",
    weave: "cashmere",
  },
  {
    id: "F-141",
    brand: "Loro Piana",
    name: "Tasmanian",
    code: "LP-TS-1902",
    color: "네이비 스트라이프",
    composition: "Wool 100% / 230g",
    stockM: 9.6,
    assignedM: 3.4,
    unitPrice: 192_000,
    status: "충분",
    leadTimeDays: 20,
    updatedAt: "2026.07.24",
    weave: "pinstripe",
  },
  {
    id: "F-150",
    brand: "Dormeuil",
    name: "Tonik 2000",
    code: "DM-TK-0761",
    color: "블랙",
    composition: "Wool 79% Mohair 21%",
    stockM: 3.1,
    assignedM: 3.0,
    unitPrice: 187_000,
    status: "재고 부족",
    leadTimeDays: 26,
    updatedAt: "2026.07.28",
    weave: "twill",
  },
  {
    id: "F-163",
    brand: "Thomas Mason",
    name: "Journey Poplin",
    code: "TM-JP-5520",
    color: "화이트",
    composition: "Cotton 100% / 120g",
    stockM: 26.5,
    assignedM: 8.1,
    unitPrice: 42_000,
    status: "충분",
    leadTimeDays: 12,
    updatedAt: "2026.07.22",
    weave: "poplin",
  },
  {
    id: "F-171",
    brand: "Holland & Sherry",
    name: "Crystal Springs",
    code: "HS-CS-3308",
    color: "딥 브라운",
    composition: "Wool 100% / 260g",
    stockM: 6.4,
    assignedM: 2.0,
    unitPrice: 208_000,
    status: "발주 완료",
    leadTimeDays: 30,
    updatedAt: "2026.07.21",
    weave: "plain",
  },
];

export const PRODUCTION_JOBS: ProductionJob[] = [
  {
    id: "PRD-441",
    orderId: "ORD-2607-018",
    customer: "김진우",
    item: "3피스 정장",
    stage: "납품",
    progress: 98,
    worker: "최봉수 재단사",
    startedAt: "2026.06.17",
    dueAt: "2026.07.29",
    riskDays: 0,
    status: "정상",
  },
  {
    id: "PRD-448",
    orderId: "ORD-2607-021",
    customer: "박지영",
    item: "재킷 · 스커트",
    stage: "가봉",
    progress: 72,
    worker: "김미정 봉제팀",
    startedAt: "2026.06.26",
    dueAt: "2026.08.12",
    riskDays: 0,
    status: "정상",
  },
  {
    id: "PRD-432",
    orderId: "ORD-2607-009",
    customer: "이도현",
    item: "예복 정장 2벌",
    stage: "제작",
    progress: 54,
    worker: "최봉수 재단사",
    startedAt: "2026.06.08",
    dueAt: "2026.08.05",
    riskDays: 3,
    status: "지연 위험",
  },
  {
    id: "PRD-419",
    orderId: "ORD-2606-039",
    customer: "오세훈",
    item: "정장 1벌 · 셔츠 2매",
    stage: "제작",
    progress: 61,
    worker: "김미정 봉제팀",
    startedAt: "2026.05.26",
    dueAt: "2026.07.25",
    riskDays: 4,
    status: "지연",
  },
  {
    id: "PRD-425",
    orderId: "ORD-2606-044",
    customer: "한재석",
    item: "캐시미어 코트",
    stage: "수정",
    progress: 88,
    worker: "정우빈 수선실",
    startedAt: "2026.06.02",
    dueAt: "2026.08.01",
    riskDays: 0,
    status: "정상",
  },
  {
    id: "PRD-455",
    orderId: "ORD-2607-033",
    customer: "정민수",
    item: "비즈니스 정장",
    stage: "치수 측정",
    progress: 12,
    worker: "이정한 실장",
    startedAt: "2026.07.26",
    dueAt: "2026.09.02",
    riskDays: 0,
    status: "정상",
  },
];

/* ────────────────────────────────────────────
   AI 소프트웨어 법인
   ──────────────────────────────────────────── */

export const AI_PROJECTS: AiProject[] = [
  {
    id: "PJ-01",
    name: "AI 맞춤 추천 플랫폼",
    product: "플랫폼",
    owner: "장태호 PM",
    phase: "PoC",
    progress: 68,
    nextMilestone: "추천 정확도 85% 검증",
    dueAt: "2026.09.18",
    status: "정상",
    headcount: 5,
    budget: 180_000_000,
    spent: 118_400_000,
    client: "롯데백화점 디지털본부",
    contractType: "PoC",
    expectedRevenue: 240_000_000,
    issue: null,
  },
  {
    id: "PJ-02",
    name: "고객 데이터 분석 시스템",
    product: "데이터",
    owner: "윤가희 리드",
    phase: "유료화",
    progress: 82,
    nextMilestone: "정식 운영 전환 · 월 구독 개시",
    dueAt: "2026.08.21",
    status: "정상",
    headcount: 4,
    budget: 132_000_000,
    spent: 104_600_000,
    client: "세아리테일",
    contractType: "유료 계약",
    expectedRevenue: 168_000_000,
    issue: null,
  },
  {
    id: "PJ-03",
    name: "이미지 인식 모델 고도화",
    product: "모델",
    owner: "정승우 리서처",
    phase: "MVP",
    progress: 47,
    nextMilestone: "학습 데이터 12만 장 확보",
    dueAt: "2026.10.09",
    status: "지연",
    headcount: 3,
    budget: 96_000_000,
    spent: 61_200_000,
    client: "내부 과제",
    contractType: "내부 과제",
    expectedRevenue: 0,
    issue: "라벨링 외주 일정 2주 지연",
  },
  {
    id: "PJ-04",
    name: "비앤테일러샵 운영 자동화",
    product: "자동화",
    owner: "한지민 PM",
    phase: "유료화",
    progress: 91,
    nextMilestone: "원단 재고 연동 모듈 배포",
    dueAt: "2026.08.07",
    status: "정상",
    headcount: 3,
    budget: 74_000_000,
    spent: 66_300_000,
    client: "비앤테일러샵 (내부)",
    contractType: "내부 과제",
    expectedRevenue: 0,
    issue: null,
  },
  {
    id: "PJ-05",
    name: "AI 상담 챗봇",
    product: "솔루션",
    owner: "장태호 PM",
    phase: "반복 판매",
    progress: 76,
    nextMilestone: "3개사 동시 온보딩",
    dueAt: "2026.09.30",
    status: "정상",
    headcount: 4,
    budget: 118_000_000,
    spent: 83_900_000,
    client: "현우제약 외 2개사",
    contractType: "유료 계약",
    expectedRevenue: 204_000_000,
    issue: null,
  },
  {
    id: "PJ-06",
    name: "데이터 분석 플랫폼",
    product: "플랫폼",
    owner: "윤가희 리드",
    phase: "기획",
    progress: 24,
    nextMilestone: "요구사항 정의서 확정",
    dueAt: "2026.11.14",
    status: "주의",
    headcount: 2,
    budget: 88_000_000,
    spent: 19_800_000,
    client: "대상 고객사 협의 중",
    contractType: "내부 과제",
    expectedRevenue: 150_000_000,
    issue: "요구사항 범위 확정 지연",
  },
  {
    id: "PJ-07",
    name: "제조 품질 예측 솔루션",
    product: "솔루션",
    owner: "정승우 리서처",
    phase: "PoC",
    progress: 39,
    nextMilestone: "현장 센서 데이터 연동",
    dueAt: "2026.10.28",
    status: "정상",
    headcount: 3,
    budget: 102_000_000,
    spent: 34_700_000,
    client: "동성정밀",
    contractType: "PoC",
    expectedRevenue: 130_000_000,
    issue: null,
  },
  {
    id: "PJ-08",
    name: "문서 자동 분류 엔진",
    product: "모델",
    owner: "한지민 PM",
    phase: "MVP",
    progress: 58,
    nextMilestone: "분류 정확도 92% 달성",
    dueAt: "2026.09.25",
    status: "정상",
    headcount: 2,
    budget: 64_000_000,
    spent: 33_100_000,
    client: "세림회계법인",
    contractType: "PoC",
    expectedRevenue: 96_000_000,
    issue: null,
  },
  {
    id: "PJ-09",
    name: "매장 방문 예측 대시보드",
    product: "데이터",
    owner: "윤가희 리드",
    phase: "MVP",
    progress: 62,
    nextMilestone: "요일별 예측 오차 10% 이내",
    dueAt: "2026.09.12",
    status: "정상",
    headcount: 2,
    budget: 52_000_000,
    spent: 30_600_000,
    client: "비앤테일러샵 (내부)",
    contractType: "내부 과제",
    expectedRevenue: 0,
    issue: null,
  },
  {
    id: "PJ-10",
    name: "AI 상담 요약 자동 기록",
    product: "자동화",
    owner: "한지민 PM",
    phase: "PoC",
    progress: 44,
    nextMilestone: "매장 3곳 시범 적용",
    dueAt: "2026.10.16",
    status: "정상",
    headcount: 2,
    budget: 46_000_000,
    spent: 17_800_000,
    client: "비앤테일러샵 외 2개사",
    contractType: "PoC",
    expectedRevenue: 60_000_000,
    issue: null,
  },
  {
    id: "PJ-11",
    name: "구독형 리포트 자동 발행",
    product: "솔루션",
    owner: "장태호 PM",
    phase: "유료화",
    progress: 87,
    nextMilestone: "월간 자동 발송 전환",
    dueAt: "2026.08.28",
    status: "정상",
    headcount: 2,
    budget: 38_000_000,
    spent: 32_400_000,
    client: "세아리테일 외 1개사",
    contractType: "유료 계약",
    expectedRevenue: 48_000_000,
    issue: null,
  },
  {
    id: "PJ-12",
    name: "멀티모달 상품 검색 엔진",
    product: "모델",
    owner: "정승우 리서처",
    phase: "기획",
    progress: 18,
    nextMilestone: "검색 품질 평가 기준 수립",
    dueAt: "2027.01.29",
    status: "정상",
    headcount: 2,
    budget: 72_000_000,
    spent: 11_200_000,
    client: "대상 고객사 협의 중",
    contractType: "내부 과제",
    expectedRevenue: 90_000_000,
    issue: null,
  },
];

export const PROJECT_PHASES = [
  "아이디어",
  "기획",
  "MVP",
  "PoC",
  "유료화",
  "반복 판매",
] as const;

export const COMMERCIALIZATION_FUNNEL = [
  { phase: "아이디어", count: 6, amount: 0 },
  { phase: "기획", count: 4, amount: 150_000_000 },
  { phase: "MVP", count: 3, amount: 96_000_000 },
  { phase: "PoC", count: 6, amount: 470_000_000 },
  { phase: "유료화", count: 9, amount: 368_000_000 },
  { phase: "반복 판매", count: 3, amount: 204_000_000 },
];

export const RND_TASKS: RndTask[] = [
  {
    id: "RND-01",
    title: "패턴 이미지 기반 원단 결함 탐지 연구",
    category: "컴퓨터 비전",
    owner: "정승우 리서처",
    agency: "중소벤처기업부",
    progress: 64,
    budget: 120_000_000,
    spent: 78_400_000,
    startedAt: "2026.03.02",
    dueAt: "2026.12.31",
    status: "정상",
    output: "논문 1편 · 특허 출원 1건",
  },
  {
    id: "RND-02",
    title: "체형 데이터 기반 사이즈 추천 알고리즘",
    category: "추천 시스템",
    owner: "윤가희 리드",
    agency: "자체 과제",
    progress: 71,
    budget: 86_000_000,
    spent: 59_600_000,
    startedAt: "2026.02.10",
    dueAt: "2026.10.31",
    status: "정상",
    output: "알고리즘 v2 · 내부 적용 완료",
  },
  {
    id: "RND-03",
    title: "소규모 사업장 특화 경량 LLM 파인튜닝",
    category: "자연어 처리",
    owner: "장태호 PM",
    agency: "정보통신산업진흥원",
    progress: 42,
    budget: 150_000_000,
    spent: 61_500_000,
    startedAt: "2026.04.01",
    dueAt: "2027.03.31",
    status: "정상",
    output: "중간 보고서 제출 예정",
  },
  {
    id: "RND-04",
    title: "매장 방문 데이터 프라이버시 보존 학습",
    category: "연합학습",
    owner: "정승우 리서처",
    agency: "자체 과제",
    progress: 28,
    budget: 64_000_000,
    spent: 17_900_000,
    startedAt: "2026.05.18",
    dueAt: "2027.02.28",
    status: "주의",
    output: "PoC 설계 단계",
  },
  {
    id: "RND-05",
    title: "수요 예측 기반 원단 발주 최적화",
    category: "시계열 예측",
    owner: "한지민 PM",
    agency: "자체 과제",
    progress: 83,
    budget: 48_000_000,
    spent: 39_800_000,
    startedAt: "2026.01.15",
    dueAt: "2026.08.31",
    status: "정상",
    output: "발주 오차 21% 감소",
  },
  {
    id: "RND-06",
    title: "음성 상담 요약 · 자동 기록",
    category: "음성 인식",
    owner: "윤가희 리드",
    agency: "자체 과제",
    progress: 55,
    budget: 42_000_000,
    spent: 23_100_000,
    startedAt: "2026.04.20",
    dueAt: "2026.11.30",
    status: "정상",
    output: "상담 기록 자동화 시범 적용",
  },
  {
    id: "RND-07",
    title: "멀티모달 상품 검색 엔진",
    category: "멀티모달",
    owner: "정승우 리서처",
    agency: "중소벤처기업부",
    progress: 36,
    budget: 98_000_000,
    spent: 31_400_000,
    startedAt: "2026.06.01",
    dueAt: "2027.05.31",
    status: "정상",
    output: "데이터셋 구축 진행",
  },
  {
    id: "RND-08",
    title: "AI 모델 운영 비용 최적화 연구",
    category: "MLOps",
    owner: "장태호 PM",
    agency: "자체 과제",
    progress: 19,
    budget: 36_000_000,
    spent: 6_800_000,
    startedAt: "2026.07.06",
    dueAt: "2027.01.31",
    status: "주의",
    output: "추론 비용 분석 착수",
  },
];

export const MEMBERS: Member[] = [
  {
    id: "M-01",
    name: "장태호",
    role: "프로젝트 총괄 PM",
    level: "리드",
    projects: ["AI 맞춤 추천 플랫폼", "AI 상담 챗봇"],
    allocation: 100,
    monthlyCost: 8_600_000,
    joinedAt: "2023.10",
    skills: ["프로덕트 기획", "LLM 응용", "고객 대응"],
  },
  {
    id: "M-02",
    name: "윤가희",
    role: "데이터 엔지니어링 리드",
    level: "리드",
    projects: ["고객 데이터 분석 시스템", "데이터 분석 플랫폼"],
    allocation: 100,
    monthlyCost: 8_200_000,
    joinedAt: "2023.11",
    skills: ["데이터 파이프라인", "BigQuery", "추천 시스템"],
  },
  {
    id: "M-03",
    name: "정승우",
    role: "AI 리서처",
    level: "시니어",
    projects: ["이미지 인식 모델 고도화", "제조 품질 예측 솔루션"],
    allocation: 90,
    monthlyCost: 7_400_000,
    joinedAt: "2024.02",
    skills: ["컴퓨터 비전", "PyTorch", "모델 경량화"],
  },
  {
    id: "M-04",
    name: "한지민",
    role: "프로덕트 PM",
    level: "시니어",
    projects: ["비앤테일러샵 운영 자동화", "문서 자동 분류 엔진"],
    allocation: 100,
    monthlyCost: 6_900_000,
    joinedAt: "2024.05",
    skills: ["업무 자동화", "요구사항 정의", "QA"],
  },
  {
    id: "M-05",
    name: "서준영",
    role: "백엔드 개발",
    level: "시니어",
    projects: ["AI 맞춤 추천 플랫폼", "고객 데이터 분석 시스템"],
    allocation: 100,
    monthlyCost: 6_600_000,
    joinedAt: "2024.03",
    skills: ["Node.js", "Kubernetes", "API 설계"],
  },
  {
    id: "M-06",
    name: "김하늘",
    role: "프론트엔드 개발",
    level: "미들",
    projects: ["AI 상담 챗봇", "비앤테일러샵 운영 자동화"],
    allocation: 100,
    monthlyCost: 5_400_000,
    joinedAt: "2024.09",
    skills: ["React", "Next.js", "디자인 시스템"],
  },
  {
    id: "M-07",
    name: "박도윤",
    role: "MLOps 엔지니어",
    level: "미들",
    projects: ["이미지 인식 모델 고도화", "AI 맞춤 추천 플랫폼"],
    allocation: 80,
    monthlyCost: 5_800_000,
    joinedAt: "2025.01",
    skills: ["MLOps", "GPU 운영", "모니터링"],
  },
  {
    id: "M-08",
    name: "이서현",
    role: "데이터 라벨링 매니저",
    level: "주니어",
    projects: ["이미지 인식 모델 고도화", "멀티모달 상품 검색 엔진"],
    allocation: 100,
    monthlyCost: 3_900_000,
    joinedAt: "2025.06",
    skills: ["데이터 품질 관리", "외주 관리"],
  },
];

export const DATA_ASSETS: DataAsset[] = [
  {
    id: "DA-01",
    name: "맞춤정장 체형 · 치수 데이터셋",
    type: "학습 데이터",
    scale: "3,240건",
    owner: "윤가희",
    status: "운영 중",
    updatedAt: "2026.07.24",
    note: "비앤테일러샵 8년치 실측 데이터 비식별화",
  },
  {
    id: "DA-02",
    name: "원단 표면 이미지 데이터셋",
    type: "학습 데이터",
    scale: "84,600장",
    owner: "이서현",
    status: "구축 중",
    updatedAt: "2026.07.27",
    note: "목표 12만 장 중 70% 확보",
  },
  {
    id: "DA-03",
    name: "사이즈 추천 모델 v2",
    type: "모델",
    scale: "정확도 87.4%",
    owner: "윤가희",
    status: "운영 중",
    updatedAt: "2026.07.18",
    note: "매장 상담 화면 실시간 연동",
  },
  {
    id: "DA-04",
    name: "결함 탐지 모델 v0.9",
    type: "모델",
    scale: "정확도 79.1%",
    owner: "정승우",
    status: "검증 중",
    updatedAt: "2026.07.22",
    note: "목표 90% 대비 개선 필요",
  },
  {
    id: "DA-05",
    name: "상담 요약 API",
    type: "API",
    scale: "월 4.2만 호출",
    owner: "장태호",
    status: "운영 중",
    updatedAt: "2026.07.26",
    note: "챗봇 · 매장 상담 공통 사용",
  },
  {
    id: "DA-06",
    name: "GPU 학습 클러스터",
    type: "인프라",
    scale: "A100 4대 (클라우드)",
    owner: "박도윤",
    status: "운영 중",
    updatedAt: "2026.07.28",
    note: "월 평균 가동률 71%",
  },
  {
    id: "DA-07",
    name: "체형 기반 의류 추천 방법 특허",
    type: "지식재산권",
    scale: "출원번호 10-2026-0043**",
    owner: "장태호",
    status: "출원 중",
    updatedAt: "2026.06.30",
    note: "심사 청구 완료",
  },
  {
    id: "DA-08",
    name: "원단 결함 탐지 방법 특허",
    type: "지식재산권",
    scale: "명세서 작성 중",
    owner: "정승우",
    status: "출원 중",
    updatedAt: "2026.07.15",
    note: "R&D-01 과제 성과물",
  },
];

export const DEALS: Deal[] = [
  {
    id: "DL-01",
    client: "롯데백화점 디지털본부",
    project: "AI 맞춤 추천 플랫폼",
    phase: "PoC",
    amount: 240_000_000,
    monthly: 0,
    startedAt: "2026.05.11",
    closeAt: "2026.10.15",
    probability: 70,
    owner: "장태호",
    status: "PoC 진행",
  },
  {
    id: "DL-02",
    client: "세아리테일",
    project: "고객 데이터 분석 시스템",
    phase: "유료화",
    amount: 168_000_000,
    monthly: 14_000_000,
    startedAt: "2026.01.20",
    closeAt: "2026.08.21",
    probability: 95,
    owner: "윤가희",
    status: "계약 완료",
  },
  {
    id: "DL-03",
    client: "현우제약",
    project: "AI 상담 챗봇",
    phase: "반복 판매",
    amount: 96_000_000,
    monthly: 8_000_000,
    startedAt: "2026.03.09",
    closeAt: "2026.09.30",
    probability: 90,
    owner: "장태호",
    status: "계약 완료",
  },
  {
    id: "DL-04",
    client: "동성정밀",
    project: "제조 품질 예측 솔루션",
    phase: "PoC",
    amount: 130_000_000,
    monthly: 0,
    startedAt: "2026.06.15",
    closeAt: "2026.11.28",
    probability: 55,
    owner: "정승우",
    status: "PoC 진행",
  },
  {
    id: "DL-05",
    client: "세림회계법인",
    project: "문서 자동 분류 엔진",
    phase: "MVP",
    amount: 96_000_000,
    monthly: 0,
    startedAt: "2026.07.02",
    closeAt: "2026.09.25",
    probability: 60,
    owner: "한지민",
    status: "제안",
  },
  {
    id: "DL-06",
    client: "우리에프앤비",
    project: "AI 상담 챗봇",
    phase: "유료화",
    amount: 72_000_000,
    monthly: 6_000_000,
    startedAt: "2026.07.14",
    closeAt: "2026.08.30",
    probability: 75,
    owner: "장태호",
    status: "계약 협의",
  },
  {
    id: "DL-07",
    client: "한성엔지니어링",
    project: "데이터 분석 플랫폼",
    phase: "기획",
    amount: 150_000_000,
    monthly: 0,
    startedAt: "2026.07.21",
    closeAt: "2026.12.20",
    probability: 35,
    owner: "윤가희",
    status: "제안",
  },
];

/* ────────────────────────────────────────────
   자금 관리
   ──────────────────────────────────────────── */

export const BUDGET_LINES: BudgetLine[] = [
  {
    id: "B-T1",
    company: "tailor",
    category: "원단 매입",
    purpose: "가을 · 겨울 시즌 원단 선매입",
    relatedProject: "2026 F/W 시즌 준비",
    planned: 72_000_000,
    executed: 48_600_000,
  },
  {
    id: "B-T2",
    company: "tailor",
    category: "부자재",
    purpose: "안감 · 단추 · 심지 · 라벨",
    relatedProject: "상시 운영",
    planned: 14_000_000,
    executed: 9_820_000,
  },
  {
    id: "B-T3",
    company: "tailor",
    category: "제작비",
    purpose: "외주 봉제 · 패턴 제작",
    relatedProject: "주문 제작 46건",
    planned: 46_000_000,
    executed: 31_400_000,
  },
  {
    id: "B-T4",
    company: "tailor",
    category: "인건비",
    purpose: "매장 · 공방 인력 11명",
    relatedProject: "상시 운영",
    planned: 38_000_000,
    executed: 38_000_000,
  },
  {
    id: "B-T5",
    company: "tailor",
    category: "마케팅",
    purpose: "VIP 고객 초청 행사 · 콘텐츠 제작",
    relatedProject: "여름 프로모션",
    planned: 18_000_000,
    executed: 7_450_000,
  },
  {
    id: "B-T6",
    company: "tailor",
    category: "매장 운영비",
    purpose: "임대료 · 관리비 · 비품",
    relatedProject: "청담 매장",
    planned: 22_000_000,
    executed: 20_100_000,
  },
  {
    id: "B-A1",
    company: "corp",
    category: "개발 인력",
    purpose: "개발 인력 25명 인건비",
    relatedProject: "전사 공통",
    planned: 138_000_000,
    executed: 132_800_000,
  },
  {
    id: "B-A2",
    company: "corp",
    category: "R&D",
    purpose: "연구 과제 8건 수행",
    relatedProject: "R&D 과제 전체",
    planned: 84_000_000,
    executed: 52_600_000,
  },
  {
    id: "B-A3",
    company: "corp",
    category: "클라우드",
    purpose: "GPU 학습 · 서비스 인프라",
    relatedProject: "전사 공통",
    planned: 32_000_000,
    executed: 26_400_000,
  },
  {
    id: "B-A4",
    company: "corp",
    category: "데이터 구축",
    purpose: "이미지 라벨링 외주 · 데이터 구매",
    relatedProject: "이미지 인식 모델 고도화",
    planned: 46_000_000,
    executed: 21_900_000,
  },
  {
    id: "B-A5",
    company: "corp",
    category: "MVP 개발",
    purpose: "신규 제품 MVP 2건 개발",
    relatedProject: "문서 자동 분류 · 데이터 분석 플랫폼",
    planned: 40_000_000,
    executed: 18_300_000,
  },
  {
    id: "B-A6",
    company: "corp",
    category: "사업화",
    purpose: "영업 · 전시 · 고객사 PoC 지원",
    relatedProject: "PoC 6건",
    planned: 26_000_000,
    executed: 12_700_000,
  },
  {
    id: "B-A7",
    company: "corp",
    category: "지식재산권",
    purpose: "특허 출원 2건 · 상표 등록",
    relatedProject: "R&D 성과물",
    planned: 12_000_000,
    executed: 5_400_000,
  },
];

export const TRANSACTIONS: Transaction[] = [
  {
    id: "TX-2607-31",
    company: "tailor",
    date: "2026.07.28",
    category: "원단 매입",
    title: "Zegna Trofeo 600 네이비 12m 발주",
    vendor: "제냐 코리아",
    amount: 2_520_000,
    method: "계좌이체",
    approver: "박정열",
    status: "집행 완료",
  },
  {
    id: "TX-2607-30",
    company: "corp",
    date: "2026.07.28",
    category: "클라우드",
    title: "7월 GPU 학습 인스턴스 사용료",
    vendor: "클라우드 서비스",
    amount: 4_180_000,
    method: "법인카드",
    approver: "박도윤",
    status: "집행 완료",
  },
  {
    id: "TX-2607-29",
    company: "corp",
    date: "2026.07.27",
    category: "데이터 구축",
    title: "원단 이미지 라벨링 외주 3차",
    vendor: "라벨웍스",
    amount: 6_400_000,
    method: "계좌이체",
    approver: "박정열",
    status: "승인 대기",
  },
  {
    id: "TX-2607-28",
    company: "tailor",
    date: "2026.07.27",
    category: "제작비",
    title: "7월 외주 봉제 정산 (18벌)",
    vendor: "성수 봉제공방",
    amount: 8_640_000,
    method: "계좌이체",
    approver: "박선우",
    status: "집행 완료",
  },
  {
    id: "TX-2607-27",
    company: "tailor",
    date: "2026.07.25",
    category: "마케팅",
    title: "VIP 고객 초청 시즌 프리뷰 행사",
    vendor: "아뜰리에 이벤트",
    amount: 3_200_000,
    method: "법인카드",
    approver: "박정열",
    status: "집행 완료",
  },
  {
    id: "TX-2607-26",
    company: "corp",
    date: "2026.07.24",
    category: "지식재산권",
    title: "체형 기반 추천 방법 특허 심사 청구",
    vendor: "정민특허법률사무소",
    amount: 2_400_000,
    method: "계좌이체",
    approver: "박정열",
    status: "집행 완료",
  },
  {
    id: "TX-2607-25",
    company: "corp",
    date: "2026.07.23",
    category: "사업화",
    title: "동성정밀 PoC 현장 장비 임차",
    vendor: "테크렌탈",
    amount: 1_850_000,
    method: "법인카드",
    approver: "정승우",
    status: "집행 완료",
  },
  {
    id: "TX-2607-24",
    company: "tailor",
    date: "2026.07.22",
    category: "부자재",
    title: "이탈리아 혼방 안감 · 호른 단추 입고",
    vendor: "동대문 부자재상사",
    amount: 1_740_000,
    method: "계좌이체",
    approver: "이정한",
    status: "집행 완료",
  },
  {
    id: "TX-2607-23",
    company: "corp",
    date: "2026.07.21",
    category: "R&D",
    title: "중기부 과제 2분기 연구 재료비",
    vendor: "연구 집행",
    amount: 12_600_000,
    method: "계좌이체",
    approver: "박정열",
    status: "집행 완료",
  },
  {
    id: "TX-2607-22",
    company: "tailor",
    date: "2026.07.20",
    category: "매장 운영비",
    title: "청담 매장 7월 임대료 · 관리비",
    vendor: "청담빌딩 관리단",
    amount: 9_800_000,
    method: "자동이체",
    approver: "자동",
    status: "집행 완료",
  },
  {
    id: "TX-2607-21",
    company: "corp",
    date: "2026.07.31",
    category: "개발 인력",
    title: "7월 급여 지급 (25명)",
    vendor: "급여 계좌",
    amount: 132_800_000,
    method: "자동이체",
    approver: "박정열",
    status: "예정",
  },
  {
    id: "TX-2607-20",
    company: "tailor",
    date: "2026.07.31",
    category: "인건비",
    title: "7월 급여 지급 (11명)",
    vendor: "급여 계좌",
    amount: 38_000_000,
    method: "자동이체",
    approver: "박정열",
    status: "예정",
  },
  {
    id: "TX-2607-19",
    company: "corp",
    date: "2026.07.30",
    category: "MVP 개발",
    title: "문서 분류 엔진 UI 외주 2차",
    vendor: "스튜디오 원",
    amount: 5_500_000,
    method: "계좌이체",
    approver: "한지민",
    status: "승인 대기",
  },
  {
    id: "TX-2607-18",
    company: "tailor",
    date: "2026.07.30",
    category: "원단 매입",
    title: "Dormeuil Amadeus 365 20m 추가 발주",
    vendor: "도메유 서울",
    amount: 3_120_000,
    method: "계좌이체",
    approver: "박정열",
    status: "승인 대기",
  },
];

/* ────────────────────────────────────────────
   일정 · 알림 · 확인 업무 · 메모
   ──────────────────────────────────────────── */

export const SCHEDULES: ScheduleItem[] = [
  {
    id: "S-01",
    company: "tailor",
    date: "2026.07.29",
    time: "10:00",
    kind: "납품",
    title: "김진우 님 3피스 정장 납품",
    place: "청담 매장",
    owner: "이정한 실장",
    done: false,
  },
  {
    id: "S-02",
    company: "tailor",
    date: "2026.07.29",
    time: "11:30",
    kind: "상담",
    title: "신규 상담 5건 (예약제)",
    place: "청담 매장",
    owner: "정하윤 매니저",
    done: false,
  },
  {
    id: "S-03",
    company: "corp",
    date: "2026.07.29",
    time: "14:00",
    kind: "회의",
    title: "AI 상담 챗봇 PoC 확대 회의",
    place: "성수 오피스",
    owner: "장태호 PM",
    done: false,
  },
  {
    id: "S-04",
    company: "corp",
    date: "2026.07.29",
    time: "16:00",
    kind: "보고",
    title: "중기부 R&D 과제 중간 보고 준비",
    place: "성수 오피스",
    owner: "정승우 리서처",
    done: false,
  },
  {
    id: "S-05",
    company: "tailor",
    date: "2026.07.29",
    time: "17:30",
    kind: "발주",
    title: "부족 원단 3종 발주 확정",
    place: "청담 매장",
    owner: "박선우 팀장",
    done: false,
  },
  {
    id: "S-06",
    company: "tailor",
    date: "2026.07.30",
    time: "11:00",
    kind: "가봉",
    title: "박지영 님 재킷 가봉",
    place: "청담 매장",
    owner: "이정한 실장",
    done: false,
  },
  {
    id: "S-07",
    company: "corp",
    date: "2026.07.30",
    time: "15:00",
    kind: "계약",
    title: "우리에프앤비 챗봇 계약 조건 협의",
    place: "고객사 방문",
    owner: "장태호 PM",
    done: false,
  },
  {
    id: "S-08",
    company: "tailor",
    date: "2026.07.31",
    time: "10:30",
    kind: "정산",
    title: "7월 매장 매출 마감 · 미수금 점검",
    place: "청담 매장",
    owner: "정하윤 매니저",
    done: false,
  },
  {
    id: "S-09",
    company: "corp",
    date: "2026.07.31",
    time: "14:00",
    kind: "회의",
    title: "8월 개발 스프린트 계획 회의",
    place: "성수 오피스",
    owner: "한지민 PM",
    done: false,
  },
  {
    id: "S-10",
    company: "tailor",
    date: "2026.08.01",
    time: "13:00",
    kind: "납품",
    title: "한재석 님 캐시미어 코트 납품",
    place: "고객 사무실",
    owner: "박선우 팀장",
    done: false,
  },
  {
    id: "S-11",
    company: "corp",
    date: "2026.08.03",
    time: "10:00",
    kind: "회의",
    title: "이미지 인식 모델 일정 재수립",
    place: "성수 오피스",
    owner: "정승우 리서처",
    done: false,
  },
  {
    id: "S-12",
    company: "tailor",
    date: "2026.08.05",
    time: "15:00",
    kind: "납품",
    title: "이도현 님 예복 2벌 납품",
    place: "청담 매장",
    owner: "박선우 팀장",
    done: false,
  },
];

export const ALERTS: AlertItem[] = [
  {
    id: "AL-01",
    company: "tailor",
    level: "긴급",
    category: "재고",
    title: "Zegna Trofeo 600 잔여 0.7m",
    detail: "배정 3.5m 대비 잔여 부족, 리드타임 21일로 즉시 발주 필요합니다.",
    at: "10분 전",
    href: "/tailor/fabrics",
    read: false,
  },
  {
    id: "AL-02",
    company: "tailor",
    level: "긴급",
    category: "납기",
    title: "오세훈 님 주문 납기 4일 초과",
    detail: "ORD-2606-039 봉제 인력 배정 지연으로 납기가 초과되었습니다.",
    at: "42분 전",
    href: "/tailor/production",
    read: false,
  },
  {
    id: "AL-03",
    company: "corp",
    level: "주의",
    category: "프로젝트",
    title: "이미지 인식 모델 일정 2주 지연",
    detail: "라벨링 외주 일정 지연으로 학습 데이터 확보가 늦어지고 있습니다.",
    at: "1시간 전",
    href: "/ai/projects",
    read: false,
  },
  {
    id: "AL-04",
    company: "corp",
    level: "주의",
    category: "자금",
    title: "데이터 구축 집행 승인 대기 2건",
    detail: "라벨링 외주 3차 6,400,000원 등 승인이 필요합니다.",
    at: "2시간 전",
    href: "/finance",
    read: false,
  },
  {
    id: "AL-05",
    company: "tailor",
    level: "안내",
    category: "고객",
    title: "재구매 예상 고객 37명 추출",
    detail: "최근 구매 주기 기준 재구매 가능성이 높은 고객이 갱신되었습니다.",
    at: "3시간 전",
    href: "/tailor/analytics",
    read: true,
  },
  {
    id: "AL-06",
    company: "corp",
    level: "안내",
    category: "계약",
    title: "우리에프앤비 계약 협의 단계 진입",
    detail: "월 6,000,000원 구독 조건으로 협의가 진행 중입니다.",
    at: "5시간 전",
    href: "/ai/biz",
    read: true,
  },
  {
    id: "AL-07",
    company: "tailor",
    level: "주의",
    category: "미수금",
    title: "미수금 38,600,000원",
    detail: "30일 초과 미수 3건이 포함되어 있습니다.",
    at: "어제",
    href: "/tailor/sales",
    read: true,
  },
  {
    id: "AL-08",
    company: "corp",
    level: "안내",
    category: "R&D",
    title: "중기부 과제 중간 보고 D-14",
    detail: "8월 12일까지 중간 보고서 제출이 필요합니다.",
    at: "어제",
    href: "/ai/rnd",
    read: true,
  },
];

export const URGENT_TASKS: TaskItem[] = [
  {
    id: "T-01",
    company: "tailor",
    title: "납기 지연",
    detail: "납기 초과 1건 · 지연 위험 2건",
    count: 3,
    due: "오늘 확인",
    level: "긴급",
    href: "/tailor/production",
  },
  {
    id: "T-02",
    company: "tailor",
    title: "원단 재고 부족",
    detail: "재고 부족 3종 · 발주 권장 2종",
    count: 5,
    due: "오늘 발주",
    level: "긴급",
    href: "/tailor/fabrics",
  },
  {
    id: "T-03",
    company: "corp",
    title: "AI 프로젝트 이슈",
    detail: "일정 지연 1건 · 범위 확정 지연 1건",
    count: 2,
    due: "금주 내",
    level: "주의",
    href: "/ai/projects",
  },
  {
    id: "T-04",
    company: "corp",
    title: "자금 집행 검토",
    detail: "승인 대기 3건 · 예정 1건",
    count: 4,
    due: "오늘 결재",
    level: "주의",
    href: "/finance",
  },
];

export const MEMOS: MemoItem[] = [
  {
    id: "MM-01",
    company: "tailor",
    text: "비앤테일러샵 가을 시즌 원단 프로모션 준비 — 8월 1주차 VIP 안내 발송",
    at: "2026.07.28",
  },
  {
    id: "MM-02",
    company: "corp",
    text: "AI 챗봇 PoC 고객사 확대 진행 — 제약 · F&B 업종 우선 접촉",
    at: "2026.07.27",
  },
  {
    id: "MM-03",
    company: "all",
    text: "양사 자금 집행 계획 주간 점검 — 매주 월요일 오전 9시 고정",
    at: "2026.07.27",
  },
  {
    id: "MM-04",
    company: "corp",
    text: "라벨링 외주 업체 이원화 검토, 단일 업체 지연 리스크 해소 필요",
    at: "2026.07.26",
  },
];

/* ────────────────────────────────────────────
   보고서
   ──────────────────────────────────────────── */

export const REPORTS = [
  {
    id: "RP-01",
    title: "2026년 7월 통합 경영 리포트",
    scope: "통합",
    period: "2026.07.01 ~ 07.29",
    author: "경영지원",
    updatedAt: "2026.07.29",
    summary: "양사 합산 매출 215,770,000원, 전월 대비 10.9% 증가",
  },
  {
    id: "RP-02",
    title: "비앤테일러샵 7월 운영 리포트",
    scope: "비앤테일러샵",
    period: "2026.07.01 ~ 07.29",
    author: "이정한 실장",
    updatedAt: "2026.07.28",
    summary: "주문 46건 · 납품 18건 · 미수금 38,600,000원",
  },
  {
    id: "RP-03",
    title: "AI 법인 사업화 진행 리포트",
    scope: "AI 법인",
    period: "2026.07.01 ~ 07.29",
    author: "장태호 PM",
    updatedAt: "2026.07.28",
    summary: "PoC 6건 · 유료 계약 9건 · 파이프라인 412,000,000원",
  },
  {
    id: "RP-04",
    title: "2026년 상반기 자금 집행 결산",
    scope: "통합",
    period: "2026.01.01 ~ 06.30",
    author: "경영지원",
    updatedAt: "2026.07.10",
    summary: "계획 대비 집행률 비앤테일러샵 64% · AI 법인 62%",
  },
  {
    id: "RP-05",
    title: "R&D 과제 중간 성과 보고",
    scope: "AI 법인",
    period: "2026.03.01 ~ 07.29",
    author: "정승우 리서처",
    updatedAt: "2026.07.22",
    summary: "과제 8건 진행, 특허 출원 2건 · 논문 1편",
  },
];

/* ────────────────────────────────────────────
   모바일 브리핑 : 오늘 확인할 업무 · 승인 대기
   ──────────────────────────────────────────── */

/** 대표자가 오늘 확인해야 하는 업무 (모바일 첫 화면 기준) */
export const TODAY_URGENT: UrgentItem[] = [
  {
    id: "U-01",
    company: "tailor",
    title: "Zegna Trofeo 600 원단 재고 부족",
    detail: "잔여 0.7m · 리드타임 21일",
    status: "발주 필요",
    level: "긴급",
    at: "10분 전",
    href: "/tailor/fabrics",
  },
  {
    id: "U-02",
    company: "tailor",
    title: "오세훈 님 주문 납기 4일 초과",
    detail: "ORD-2606-039 · 봉제 인력 배정 지연",
    status: "납기 초과",
    level: "긴급",
    at: "42분 전",
    href: "/tailor/production",
  },
  {
    id: "U-03",
    company: "corp",
    title: "AI 맞춤 추천 플랫폼 중간 점검 D-3",
    detail: "롯데백화점 PoC · 정확도 85% 검증",
    status: "마감 임박",
    level: "주의",
    at: "1시간 전",
    href: "/ai/projects",
  },
  {
    id: "U-04",
    company: "corp",
    title: "개발 인력 채용 승인 필요",
    detail: "MLOps 엔지니어 1명 · 8월 입사 예정",
    status: "승인 대기",
    level: "주의",
    at: "2시간 전",
    href: "/ai/people",
  },
  {
    id: "U-05",
    company: "tailor",
    title: "이도현 님 예복 제작 지연 위험",
    detail: "원단 추가 입고 대기 · 납기 3일 여유",
    status: "지연 위험",
    level: "주의",
    at: "3시간 전",
    href: "/tailor/production",
  },
  {
    id: "U-06",
    company: "corp",
    title: "이미지 인식 모델 일정 재수립",
    detail: "라벨링 외주 2주 지연",
    status: "일정 조정",
    level: "주의",
    at: "어제",
    href: "/ai/projects",
  },
];

/** 대표자 승인 대기 업무 */
export const APPROVALS: ApprovalItem[] = [
  {
    id: "AP-01",
    company: "corp",
    kind: "자금 집행 승인",
    title: "원단 이미지 라벨링 외주 3차",
    detail: "라벨웍스 · 데이터 구축",
    amount: 6_400_000,
    requestedBy: "이서현",
    at: "2시간 전",
    href: "/finance",
  },
  {
    id: "AP-02",
    company: "tailor",
    kind: "자금 집행 승인",
    title: "Dormeuil Amadeus 365 20m 추가 발주",
    detail: "도메유 서울 · 원단 매입",
    amount: 3_120_000,
    requestedBy: "박선우",
    at: "3시간 전",
    href: "/finance",
  },
  {
    id: "AP-03",
    company: "corp",
    kind: "자금 집행 승인",
    title: "문서 분류 엔진 UI 외주 2차",
    detail: "스튜디오 원 · MVP 개발",
    amount: 5_500_000,
    requestedBy: "한지민",
    at: "어제",
    href: "/finance",
  },
  {
    id: "AP-04",
    company: "tailor",
    kind: "주문 승인",
    title: "이도현 님 예복 2벌 추가 제작",
    detail: "Dormeuil Amadeus 365 · 납기 8월 5일",
    amount: 7_400_000,
    requestedBy: "이정한",
    at: "어제",
    href: "/tailor/orders",
  },
  {
    id: "AP-05",
    company: "tailor",
    kind: "주문 승인",
    title: "최유리 님 팬츠수트 원단 변경",
    detail: "VBC Perennial → Loro Piana Super 130's",
    amount: 3_480_000,
    requestedBy: "정하윤",
    at: "어제",
    href: "/tailor/orders",
  },
  {
    id: "AP-06",
    company: "corp",
    kind: "프로젝트 일정 변경",
    title: "이미지 인식 모델 완료일 2주 연기",
    detail: "2026.10.09 → 2026.10.23",
    amount: null,
    requestedBy: "정승우",
    at: "1일 전",
    href: "/ai/projects",
  },
  {
    id: "AP-07",
    company: "corp",
    kind: "보고서 확인",
    title: "AI 법인 사업화 진행 리포트",
    detail: "2026.07.01 ~ 07.29",
    amount: null,
    requestedBy: "장태호",
    at: "2일 전",
    href: "/reports",
  },
  {
    id: "AP-08",
    company: "tailor",
    kind: "보고서 확인",
    title: "비앤테일러샵 7월 운영 리포트",
    detail: "2026.07.01 ~ 07.29",
    amount: null,
    requestedBy: "이정한",
    at: "2일 전",
    href: "/reports",
  },
];

export const APPROVAL_KINDS = [
  "자금 집행 승인",
  "주문 승인",
  "프로젝트 일정 변경",
  "보고서 확인",
] as const;

/* ────────────────────────────────────────────
   비앤테일러샵 상품 라인업
   ──────────────────────────────────────────── */

export const PRODUCTS: Product[] = [
  {
    id: "P-01",
    name: "시그니처 3피스 정장",
    category: "정장",
    garment: "suit",
    image: "/products/p01-signature-3piece.webp",
    fabricId: "F-101",
    fabricLabel: "Ermenegildo Zegna Trofeo 600",
    color: "네이비",
    weave: "herringbone",
    priceFrom: 4_850_000,
    leadDays: 35,
    monthlyOrders: 12,
    stockM: 0.7,
    status: "원단 부족",
    note: "라펠 폭 · 안감 색상 선택 가능",
  },
  {
    id: "P-02",
    name: "비즈니스 투피스 정장",
    category: "정장",
    garment: "suit",
    image: "/products/p02-business-2piece.webp",
    fabricId: "F-141",
    fabricLabel: "Loro Piana Tasmanian",
    color: "네이비 스트라이프",
    weave: "pinstripe",
    priceFrom: 3_250_000,
    leadDays: 30,
    monthlyOrders: 18,
    stockM: 6.2,
    status: "제작 가능",
    note: "사계절용 230g 원단",
  },
  {
    id: "P-03",
    name: "캐시미어 블렌드 코트",
    category: "코트",
    garment: "coat",
    image: "/products/p03-cashmere-coat.webp",
    fabricId: "F-130",
    fabricLabel: "Ermenegildo Zegna 15milmil15",
    color: "카멜",
    weave: "cashmere",
    priceFrom: 5_600_000,
    leadDays: 42,
    monthlyOrders: 6,
    stockM: 1.8,
    status: "제작 가능",
    note: "캐시미어 10% 혼방 · 가을 시즌",
  },
  {
    id: "P-04",
    name: "여성 팬츠수트",
    category: "여성",
    garment: "pantsuit",
    image: "/products/p04-women-pantsuit.webp",
    fabricId: "F-108",
    fabricLabel: "Loro Piana Super 130's",
    color: "블랙",
    weave: "twill",
    priceFrom: 3_620_000,
    leadDays: 32,
    monthlyOrders: 9,
    stockM: 0.7,
    status: "원단 부족",
    note: "어깨 패드 최소화 패턴",
  },
  {
    id: "P-05",
    name: "블랙 턱시도",
    category: "예복",
    garment: "tuxedo",
    image: "/products/p05-black-tuxedo.webp",
    fabricId: "F-150",
    fabricLabel: "Dormeuil Tonik 2000",
    color: "블랙",
    weave: "twill",
    priceFrom: 5_200_000,
    leadDays: 45,
    monthlyOrders: 4,
    stockM: 0.1,
    status: "예약 마감",
    note: "모헤어 21% · 새틴 라펠",
  },
  {
    id: "P-06",
    name: "맞춤 드레스 셔츠",
    category: "셔츠",
    garment: "shirt",
    image: "/products/p06-dress-shirt.webp",
    fabricId: "F-163",
    fabricLabel: "Thomas Mason Journey Poplin",
    color: "화이트",
    weave: "poplin",
    priceFrom: 350_000,
    leadDays: 14,
    monthlyOrders: 34,
    stockM: 18.4,
    status: "제작 가능",
    note: "칼라 형태 6종 선택",
  },
  {
    id: "P-07",
    name: "미드나잇 예복 정장",
    category: "예복",
    garment: "suit",
    image: "/products/p07-midnight-formal.webp",
    fabricId: "F-115",
    fabricLabel: "Dormeuil Amadeus 365",
    color: "미드나잇 블루",
    weave: "herringbone",
    priceFrom: 3_700_000,
    leadDays: 38,
    monthlyOrders: 7,
    stockM: 2.8,
    status: "제작 가능",
    note: "예식 · 행사용 라인",
  },
  {
    id: "P-08",
    name: "라이트 그레이 정장",
    category: "정장",
    garment: "suit",
    image: "/products/p08-light-grey-suit.webp",
    fabricId: "F-122",
    fabricLabel: "Vitale Barberis Canonico Perennial",
    color: "라이트 그레이",
    weave: "plain",
    priceFrom: 2_980_000,
    leadDays: 28,
    monthlyOrders: 11,
    stockM: 12.2,
    status: "제작 가능",
    note: "봄 · 여름 240g 원단",
  },
];

export const PRODUCT_CATEGORIES = ["전체", "정장", "코트", "셔츠", "예복", "여성"] as const;
