"use client";

import {
  AlertTriangle,
  ArrowRight,
  ArrowUpRight,
  Banknote,
  Bell,
  Building2,
  CalendarDays,
  Check,
  CheckSquare,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Database,
  FileText,
  FlaskConical,
  FolderKanban,
  Gauge,
  Handshake,
  Home,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  PieChart,
  Receipt,
  Scissors,
  Shirt,
  Smartphone,
  TrendingUp,
  Users,
  UsersRound,
  Wallet,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  AlertTriangle,
  ArrowRight,
  ArrowUpRight,
  Banknote,
  Bell,
  Building2,
  CalendarDays,
  Check,
  CheckSquare,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Database,
  FileText,
  FlaskConical,
  FolderKanban,
  Gauge,
  Handshake,
  Home,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  PieChart,
  Receipt,
  Scissors,
  Shirt,
  Smartphone,
  TrendingUp,
  Users,
  UsersRound,
  Wallet,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const C = MAP[name] ?? LayoutGrid;
  return <C className={className} />;
}
